#ifndef WORLDCONSTANTS_H
#define WORLDCONSTANTS_H

constexpr int
CHUNK_W = 16,
CHUNK_D = 16,
CHUNK_H = 150,
CHUNK_AREA = CHUNK_W * CHUNK_D,
CHUNK_VOL = CHUNK_AREA * CHUNK_H,

MAX_CHUNK_XZ = 1000,
WORLD_BORDER = CHUNK_W * MAX_CHUNK_XZ,

DWG_SEA_LEVEL = 50,
DWG_MOUNTAIN_LEVEL = 95,
DWG_MIN_HEIGHT = 20,
DWG_MAX_HEIGHT = 90;

#endif